// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Loading: typeof import('element-plus/es')['ElLoadingDirective']
    MenuItem: typeof import('./src/components/XhSidebar/MenuItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarItem: typeof import('./src/components/XhSidebar/SidebarItem.vue')['default']
    SidebarMenu: typeof import('./src/components/XhSidebar/SidebarMenu.vue')['default']
    XhBreadcrumb: typeof import('./src/components/XhBreadcrumb/index.vue')['default']
    XhCard: typeof import('./src/components/XhCard/index.vue')['default']
    XhCharts: typeof import('./src/components/XhCharts/index.vue')['default']
    XhDraggable: typeof import('./src/components/XhDraggable/index.vue')['default']
    XhHamburger: typeof import('./src/components/XhHamburger/index.vue')['default']
    XhIconView: typeof import('./src/components/XhIconView/index.vue')['default']
    XhLangSelect: typeof import('./src/components/XhLangSelect/index.vue')['default']
    XhMessage: typeof import('./src/components/XhMessage/index.vue')['default']
    XhScreenfull: typeof import('./src/components/XhScreenfull/index.vue')['default']
    XhSettingSelect: typeof import('./src/components/XhSettingSelect/index.vue')['default']
    XhSvg: typeof import('./src/components/XhSvg/index.vue')['default']
    XhTable: typeof import('./src/components/XhTable/index.vue')['default']
    XhTagView: typeof import('./src/components/XhTagView/index.vue')['default']
    XhThemeSelect: typeof import('./src/components/XhThemeSelect/index.vue')['default']
  }
}

export {}
