version: '3.8'

networks:
  xhuicloud_xhuicloud:
    external: true

services:
  xhuicloud-ui:
    build:
      context: .
    restart: always
    container_name: xhuicloud-ui
    image: xhuicloud-ui
    networks:
      - xhuicloud_xhuicloud
    external_links:
      - xhuicloud-gateway
    ports:
      - 80:80
